 ruby:2.2

RUN apt-get update && apt-get -y install build-essential mysql-client libmysqlclient-dev libxml2-dev libxslt-dev git-core curl rubygems

ENV RAILS_VERSION 4.2.1
RUN gem install rails --version "$RAILS_VERSION"

RUN git clone https://github.com/Stmu/thingspeak.git && echo "helloyy huhuhu"

RUN RAILS_ENV=development && cd thingspeak && bundler update && bundle install
RUN RAILS_ENV=development && cp thingspeak/config/database.yml.example thingspeak/config/database.yml
RUN RAILS_ENV=development && cd thingspeak && rake db:create --trace
RUN RAILS_ENV=development && cd thingspeak && rake db:schema:load --trace
RUN cd thingspeak && rails server
