db:
  image: postgres:9.3
  ports:
    - "5432"
  expose:
   - "5432:5432"
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres


web:
  build: .
  command: bundle exec rails s -p 3002 -b '0.0.0.0'
  volumes:
    - .:/thingspeak
  ports:
    - "3000:3002"
  links:
    - db
  environment:
    RAILS_ENV: development
    
#db:
#  image: postgres:9.3
#  ports:
#    - "5432"
#  expose:
#   - "5432:5432"
#  environment:
#    POSTGRES_USER: postgres
#    POSTGRES_PASSWORD: postgres
